### ISSUE TITLE
polars reading parquet file?

### ISSUE THREAD

**Issue by ijlyttle** [rgbkrk/display.js#10]
Hi,

Please forgive me if this is the wrong place to ask such a question - I just came from your [Deno Sessions video](https://www.youtube.com/watch?v=b5OKkMuue3Q) and had been riffing off of your [Polars notebook example](https://github.com/rgbkrk/display.js/blob/main/test-notebooks/polars-df.ipynb) (in a VSCode Jupyter notebook FWIW).

This is very exciting stuff, and I appreciate this repository and your Noteable notebooks, thanks!

No problem to get the deno kernel hooked up, load polars, and create and `display()` a small DataFrame.

Where I am having trouble is to read a remote parquet file, e.g.:

```typescript
import pl from "npm:nodejs-polars";
import { Buffer } from "https://deno.land/std@0.202.0/io/buffer.ts";

let response = await fetch("https://llimllib.github.io/nba_data/players_2023.parquet",);
let data = await response.arrayBuffer();
let dataBuffer = new Buffer(data);

let df = pl.readParquet(dataBuffer);
```

```
Stack trace:
Error: must supply either a path or body
    at Object.readParquet (file:///Users/ijlyttle/Library/Caches/deno/npm/registry.npmjs.org/nodejs-polars/0.8.2/bin/io.js:182:15)
    at <anonymous>:2:13
```

From what I can gather, [there are differences between Deno buffers and node buffers](https://deno.land/std@0.202.0/io/buffer.ts?s=Buffer); I wonder if Polars is expecting a node buffer.

Any words of wisdom you can provide (including re-directing me elsewhere to ask the question) would be much appreciated.

Thanks!

**Comment by bartlomieju** [comment]
@ijlyttle if Polars requires Node `Buffer` then you can do: `import { Buffer } from "node:buffer";`. The `Buffer` class you are loading is Deno implementation that is not related to Node's `Buffer`.

**Comment by ijlyttle** [comment]
@bartlomieju Thanks! I got things working using `node::buffer` 🎉

I'm still fumbling my way around deno; I appreciate the pointer. I'll close this issue, but if I can make an interesting notebook using a remotely-loaded parquet file, I'll make a PR.

**Comment by rgbkrk** [comment]
We're in brand new exciting uncharted territory here so I'm happy for you to open issues like this while we're in `--unstable`. So that it doesn't get in the way of development of `display` though maybe we can move future discussions to [denotebooks](https://github.com/rgbkrk/denotebooks).

It's been a little awkward to figure out how I go between the multiple kinds of streams and buffers. I hope some good patterns emerge. I would hope we could stream it in. It doesn't help that polars must cross boundaries into compiled Rust code that needs the whole byte array. Oh well! We can work with what we've got.

I also wish that polars had the equivalent to `pd.read_csv` or `pd.read_parquet`, which loads from a URL path to include S3 or `http` schemes. There's a whole lot we can unlock.

Now... for an example of doing Parquet on S3 -> Buffer -> Polars

## ETL with Polars in Deno

Here's how I'm currently loading from parquet from S3 (with relevant internal fields out). Note that this code assumes that the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are set.

### Listing Parquet Files in S3

```typescript
import { S3, ListObjectsCommand, GetObjectCommand } from "npm:@aws-sdk/client-s3";

const client = new S3({region: 'us-east-1'});
const s3Client = client

const input = {
  Bucket: DATA_BUCKET,
  EncodingType: "url",
  MaxKeys: 100,
  Prefix: "datasets/example_table/",
};

// Note: I know I only have one parquet file in here but I'm listing them all out
const command = new ListObjectsCommand(input);
const response = await client.send(command);
const parquets = response.Contents.map(obj => obj.Key)
const getObjectResult = await client.getObject({
  Bucket: DATA_BUCKET,
  Key: parquets[0],
});
getObjectResult
```

### Load parquet into a node `Buffer`

```typescript
import { GetObjectCommand, S3Client } from "npm:@aws-sdk/client-s3";
import { Buffer } from "node:buffer";

const chunkSize = 10*1024 * 1024; // Size of each chunk in bytes

export const getObjectRange = async ({ bucket, key, start, end }) => {
  const command = new GetObjectCommand({
    Bucket: bucket,
    Key: key,
    Range: `bytes=${start}-${end}`,
  });

  return await s3Client.send(command);
};

export const getRangeAndLength = (contentRange: string) => {
  const [range, length] = contentRange.split("/");
  const [start, end] = range.split("-");
  return {
    start: parseInt(start),
    end: parseInt(end),
    length: parseInt(length),
  };
};

export const isComplete = ({ end, length }) => end === length - 1;

// Function to download S3 object in chunks and accumulate them in a buffer
export const downloadInChunks = async ({ bucket, key }): Promise<Buffer> => {
  let fullBuffer = Buffer.alloc(0); // Initialize an empty buffer to accumulate the chunks
  let rangeAndLength = { start: -1, end: -1, length: -1 };

  while (!isComplete(rangeAndLength)) {
    const { end } = rangeAndLength;
    const nextRange = { start: end + 1, end: end + chunkSize };

    console.log(`Downloading bytes ${nextRange.start} to ${nextRange.end}`);

    const { ContentRange, Body } = await getObjectRange({
      bucket,
      key,
      ...nextRange,
    });

    // Use transformToByteArray() to get a Uint8Array and convert it to a Buffer
    const byteArray = await Body.transformToByteArray();
    const chunkBuffer = Buffer.from(byteArray);

    fullBuffer = Buffer.concat([fullBuffer, chunkBuffer]); // Concatenate the new chunk to the full buffer

    rangeAndLength = getRangeAndLength(ContentRange);
  }

  return fullBuffer;
};

const bucket = DATA_BUCKET;
const key = parquets[0];

const dataBuffer = await downloadInChunks({ bucket, key });
// Now, dataBuffer contains the entire file's contents
console.log("Download complete, data length:", dataBuffer.length);
```

### From `Buffer` to `DataFrame`

```typescript
import pl from 'npm:nodejs-polars';

let example = pl.readParquet(dataBuffer)
```

I would have done all of this with either pandas or awswrangler in Python. Not sure how I'd be doing this in deno land.

**Comment by ijlyttle** [comment]
@rgbkrk Thanks for the detailed response, these are exciting times! 

I'll certainly begin any future discussions at [denotebooks](https://github.com/rgbkrk/denotebooks), and keep an eye open over there.

**Comment by rgbkrk** [comment]
Looks like polars is about to get even better for fetching data: https://x.com/datapolars/status/1707299798921933112?s=46&t=Lh9maTLxDh_i4KF92ZI3Mg
